name: FileTransfer

on:
  push:
    branches:
      - File_Transfer
  pull_request:
   branches:
       -File_Transfer
jobs:
  run_code:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.4'  

      - name: FileTransfer
        run: .\File_Transfer.py

